const questionBank = {
    // PRIMARY SCHOOL
    'Pry1': {
        'Mathematics': [
            {question:"2 + 2 = ?", a:"3", b:"4", c:"5", d:"6", correct:"b"},
            {question:"5 x 6 = ?", a:"30", b:"25", c:"40", d:"20", correct:"a"}
        ],
        'English': [{question:"The word that rhymes with 'cat' is _____.", a:"Cot", b:"Cut", c:"Bat", d:"Kit", correct:"c"},
{question:"A group of words that has a subject and a verb and makes complete sense is called a _____.", a:"Phrase", b:"Clause", c:"Sentence", d:"Paragraph", correct:"b"},
{question:"The past tense of 'teach' is _____.", a:"Teached", b:"Taught", c:"Teachd", d:"Thought", correct:"b"},
{question:"An adjective is a word that _____.", a:"Shows action", b:"Describes a noun", c:"Joins two words", d:"Replaces a noun", correct:"b"},
{question:"'The man is very tall.' The word 'very' in this sentence is an _____.", a:"Noun", b:"Adverb", c:"Verb", d:"Interjection", correct:"b"},
{question:"The feminine gender of 'actor' is _____.", a:"Actress", b:"Actorine", c:"Actoress", d:"Actrix", correct:"a"},
{question:"A sentence that expresses a strong emotion ends with a(n) _____.", a:"Full stop", b:"Question mark", c:"Exclamation mark", d:"Comma", correct:"c"},
{question:"The plural form of 'child' is _____.", a:"Childs", b:"Childes", c:"Children", d:"Childrens", correct:"c"},
{question:"Which of these is a proper noun?", a:"City", b:"River", c:"Lagos", d:"Teacher", correct:"c"},
{question:"The word 'beautiful' is an example of a(n) _____.", a:"Noun", b:"Verb", c:"Adjective", d:"Adverb", correct:"c"},
{question:"The part of a letter that contains the message is the _____.", a:"Salutation", b:"Body", c:"Closing", d:"Heading", correct:"b"},
{question:"He _____ to school every day.", a:"Go", b:"Goes", c:"Going", d:"Gone", correct:"b"},
{question:"Which word is a synonym for 'happy'?", a:"Sad", b:"Joyful", c:"Angry", d:"Tired", correct:"b"},
{question:"A word that means the opposite of another word is called a(n) _____.", a:"Synonym", b:"Homonym", c:"Antonym", d:"Acronym", correct:"c"},
{question:"'We are going to the market.' The pronoun in this sentence is _____.", a:"We", b:"going", c:"market", d:"the", correct:"a"},
{question:"Which of the following is a vowel?", a:"b", b:"c", c:"a", d:"d", correct:"c"},
{question:"A long narrative fictional story is a _____.", a:"Poem", b:"Novel", c:"Play", d:"Letter", correct:"b"},
{question:"'She sings beautifully.' The word 'beautifully' tells us _____.", a:"Where", b:"When", c:"How", d:"Why", correct:"c"},
{question:"The tense used to express an action that has already happened is _____.", a:"Present", b:"Future", c:"Past", d:"Continuous", correct:"c"},
{question:"Which punctuation mark is used to ask a question?", a:"Full stop", b:"Comma", c:"Question mark", d:"Exclamation mark", correct:"c"},
{question:"The word that rhymes with 'cat' is _____.", a:"Cot", b:"Cut", c:"Bat", d:"Kit", correct:"c"},
{question:"A group of words that has a subject and a verb and makes complete sense is called a _____.", a:"Phrase", b:"Clause", c:"Sentence", d:"Paragraph", correct:"b"},
{question:"The past tense of 'teach' is _____.", a:"Teached", b:"Taught", c:"Teachd", d:"Thought", correct:"b"},
{question:"An adjective is a word that _____.", a:"Shows action", b:"Describes a noun", c:"Joins two words", d:"Replaces a noun", correct:"b"},
{question:"'The man is very tall.' The word 'very' in this sentence is an _____.", a:"Noun", b:"Adverb", c:"Verb", d:"Interjection", correct:"b"},
{question:"The feminine gender of 'actor' is _____.", a:"Actress", b:"Actorine", c:"Actoress", d:"Actrix", correct:"a"},
{question:"A sentence that expresses a strong emotion ends with a(n) _____.", a:"Full stop", b:"Question mark", c:"Exclamation mark", d:"Comma", correct:"c"},
{question:"The plural form of 'child' is _____.", a:"Childs", b:"Childes", c:"Children", d:"Childrens", correct:"c"},
{question:"Which of these is a proper noun?", a:"City", b:"River", c:"Lagos", d:"Teacher", correct:"c"},
{question:"The word 'beautiful' is an example of a(n) _____.", a:"Noun", b:"Verb", c:"Adjective", d:"Adverb", correct:"c"},
{question:"The part of a letter that contains the message is the _____.", a:"Salutation", b:"Body", c:"Closing", d:"Heading", correct:"b"},
{question:"He _____ to school every day.", a:"Go", b:"Goes", c:"Going", d:"Gone", correct:"b"},
{question:"Which word is a synonym for 'happy'?", a:"Sad", b:"Joyful", c:"Angry", d:"Tired", correct:"b"},
{question:"A word that means the opposite of another word is called a(n) _____.", a:"Synonym", b:"Homonym", c:"Antonym", d:"Acronym", correct:"c"},
{question:"'We are going to the market.' The pronoun in this sentence is _____.", a:"We", b:"going", c:"market", d:"the", correct:"a"},
{question:"Which of the following is a vowel?", a:"b", b:"c", c:"a", d:"d", correct:"c"},
{question:"A long narrative fictional story is a _____.", a:"Poem", b:"Novel", c:"Play", d:"Letter", correct:"b"},
{question:"'She sings beautifully.' The word 'beautifully' tells us _____.", a:"Where", b:"When", c:"How", d:"Why", correct:"c"},
{question:"The tense used to express an action that has already happened is _____.", a:"Present", b:"Future", c:"Past", d:"Continuous", correct:"c"},
{question:"Which punctuation mark is used to ask a question?", a:"Full stop", b:"Comma", c:"Question mark", d:"Exclamation mark", correct:"c"}],
        'Basic Science': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': [],
        'CCA': [],
        'Home Economics': [],
        'Quantitative Reasoning': [],
        'Verbal Reasoning': []
    },
    'Pry2': {},
    'Pry3': {},
    'Pry4': {},
    'Pry5': {},

    // JUNIOR SECONDARY
    'JSS1': {
        'Mathematics': [],
        'English': [
            {question:"Who wrote 'Things Fall Apart'?", a:"Achebe", b:"Shakespeare", c:"Soyinka", d:"Dickens", correct:"a"}
        ],
        'Basic Science': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': [],
        'CCA': [],
        'Business Studies': [],
        'Espanol': [],
        'Agric': [],
        'Home Economics': []
    },
    'JSS2': {},
    'JSS3': {},

    // SENIOR SECONDARY
    'SS1': {
        'Mathematics': [],
        'English': [],
        'Biology': [],
        'Physics': [],
        'Chemistry': [],
        'Government': [],
        'Literature': [],
        'Geography': [],
        'Commerce': [],
        'Marketing': [],
        'Financial Accounting': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': []
    },
    'SS2': {},
    'SS3': {}
};