const questionBank = {
    // PRIMARY SCHOOL
    'Pry1': {
        'Mathematics': [
            {question:"2 + 2 = ?", a:"3", b:"4", c:"5", d:"6", correct:"b"},
            {question:"5 x 6 = ?", a:"30", b:"25", c:"40", d:"20", correct:"a"}
        ],
        'English': [],
        'Basic Science': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': [],
        'CCA': [],
        'Home Economics': [],
        'Quantitative Reasoning': [],
        'Verbal Reasoning': []
    },
    'Pry2': {},
    'Pry3': {},
    'Pry4': {},
    'Pry5': {},

    // JUNIOR SECONDARY
    'JSS1': {
        'Mathematics': [],
        'English': [{question:"The word that rhymes with 'cat' is _____.", a:"Cot", b:"Cut", c:"Bat", d:"Kit", correct:"c"},
{question:"A group of words that has a subject and a verb and makes complete sense is called a _____.", a:"Phrase", b:"Clause", c:"Sentence", d:"Paragraph", correct:"b"},
{question:"The past tense of 'teach' is _____.", a:"Teached", b:"Taught", c:"Teachd", d:"Thought", correct:"b"},
{question:"An adjective is a word that _____.", a:"Shows action", b:"Describes a noun", c:"Joins two words", d:"Replaces a noun", correct:"b"},
{question:"'The man is very tall.' The word 'very' in this sentence is an _____.", a:"Noun", b:"Adverb", c:"Verb", d:"Interjection", correct:"b"},
{question:"The feminine gender of 'actor' is _____.", a:"Actress", b:"Actorine", c:"Actoress", d:"Actrix", correct:"a"},
{question:"A sentence that expresses a strong emotion ends with a(n) _____.", a:"Full stop", b:"Question mark", c:"Exclamation mark", d:"Comma", correct:"c"},
{question:"The plural form of 'child' is _____.", a:"Childs", b:"Childes", c:"Children", d:"Childrens", correct:"c"},
{question:"Which of these is a proper noun?", a:"City", b:"River", c:"Lagos", d:"Teacher", correct:"c"},
{question:"The word 'beautiful' is an example of a(n) _____.", a:"Noun", b:"Verb", c:"Adjective", d:"Adverb", correct:"c"},
{question:"The part of a letter that contains the message is the _____.", a:"Salutation", b:"Body", c:"Closing", d:"Heading", correct:"b"},
{question:"He _____ to school every day.", a:"Go", b:"Goes", c:"Going", d:"Gone", correct:"b"},
{question:"Which word is a synonym for 'happy'?", a:"Sad", b:"Joyful", c:"Angry", d:"Tired", correct:"b"},
{question:"A word that means the opposite of another word is called a(n) _____.", a:"Synonym", b:"Homonym", c:"Antonym", d:"Acronym", correct:"c"},
{question:"'We are going to the market.' The pronoun in this sentence is _____.", a:"We", b:"going", c:"market", d:"the", correct:"a"},
{question:"Which of the following is a vowel?", a:"b", b:"c", c:"a", d:"d", correct:"c"},
{question:"A long narrative fictional story is a _____.", a:"Poem", b:"Novel", c:"Play", d:"Letter", correct:"b"},
{question:"'She sings beautifully.' The word 'beautifully' tells us _____.", a:"Where", b:"When", c:"How", d:"Why", correct:"c"},
{question:"The tense used to express an action that has already happened is _____.", a:"Present", b:"Future", c:"Past", d:"Continuous", correct:"c"},
{question:"Which punctuation mark is used to ask a question?", a:"Full stop", b:"Comma", c:"Question mark", d:"Exclamation mark", correct:"c"},
{question:"The word that rhymes with 'cat' is _____.", a:"Cot", b:"Cut", c:"Bat", d:"Kit", correct:"c"},
{question:"A group of words that has a subject and a verb and makes complete sense is called a _____.", a:"Phrase", b:"Clause", c:"Sentence", d:"Paragraph", correct:"b"},
{question:"The past tense of 'teach' is _____.", a:"Teached", b:"Taught", c:"Teachd", d:"Thought", correct:"b"},
{question:"An adjective is a word that _____.", a:"Shows action", b:"Describes a noun", c:"Joins two words", d:"Replaces a noun", correct:"b"},
{question:"'The man is very tall.' The word 'very' in this sentence is an _____.", a:"Noun", b:"Adverb", c:"Verb", d:"Interjection", correct:"b"},
{question:"The feminine gender of 'actor' is _____.", a:"Actress", b:"Actorine", c:"Actoress", d:"Actrix", correct:"a"},
{question:"A sentence that expresses a strong emotion ends with a(n) _____.", a:"Full stop", b:"Question mark", c:"Exclamation mark", d:"Comma", correct:"c"},
{question:"The plural form of 'child' is _____.", a:"Childs", b:"Childes", c:"Children", d:"Childrens", correct:"c"},
{question:"Which of these is a proper noun?", a:"City", b:"River", c:"Lagos", d:"Teacher", correct:"c"},
{question:"The word 'beautiful' is an example of a(n) _____.", a:"Noun", b:"Verb", c:"Adjective", d:"Adverb", correct:"c"},
{question:"The part of a letter that contains the message is the _____.", a:"Salutation", b:"Body", c:"Closing", d:"Heading", correct:"b"},
{question:"He _____ to school every day.", a:"Go", b:"Goes", c:"Going", d:"Gone", correct:"b"},
{question:"Which word is a synonym for 'happy'?", a:"Sad", b:"Joyful", c:"Angry", d:"Tired", correct:"b"},
{question:"A word that means the opposite of another word is called a(n) _____.", a:"Synonym", b:"Homonym", c:"Antonym", d:"Acronym", correct:"c"},
{question:"'We are going to the market.' The pronoun in this sentence is _____.", a:"We", b:"going", c:"market", d:"the", correct:"a"},
{question:"Which of the following is a vowel?", a:"b", b:"c", c:"a", d:"d", correct:"c"},
{question:"A long narrative fictional story is a _____.", a:"Poem", b:"Novel", c:"Play", d:"Letter", correct:"b"},
{question:"'She sings beautifully.' The word 'beautifully' tells us _____.", a:"Where", b:"When", c:"How", d:"Why", correct:"c"},
{question:"The tense used to express an action that has already happened is _____.", a:"Present", b:"Future", c:"Past", d:"Continuous", correct:"c"},
{question:"Which punctuation mark is used to ask a question?", a:"Full stop", b:"Comma", c:"Question mark", d:"Exclamation mark", correct:"c"}],
        'Basic Science': [],
        'PHE': [ {question:"Physical education is the education of the _____.", a:"Mind only", b:"Body only", c:"Body and mind through physical activity", d:"Spirit", correct:"c"},
    {question:"Which of these is a locomotor movement?", a:"Bending", b:"Twisting", c:"Running", d:"Stretching", correct:"c"},
    {question:"The ability to perform daily activities without fatigue is called _____.", a:"Physical fitness", b:"Physical education", c:"Recreation", d:"Sports", correct:"a"},
    {question:"Which of these is a component of physical fitness?", a:"Agility", b:"Intelligence", c:"Creativity", d:"Memory", correct:"a"},
    {question:"The food that builds the body is called _____.", a:"Carbohydrates", b:"Fats", c:"Proteins", d:"Vitamins", correct:"c"},
    {question:"Which of these is a field event in athletics?", a:"100m race", b:"Shot put", c:"4x100m relay", d:"Hurdles", correct:"b"},
    {question:"The organ that pumps blood around the body is the _____.", a:"Lung", b:"Brain", c:"Heart", d:"Kidney", correct:"c"},
    {question:"Which of these is a warm-up exercise?", a:"Sprinting", b:"Jogging", c:"Weightlifting", d:"Long jump", correct:"b"},
    {question:"The system that consists of the heart, blood, and blood vessels is called the _____ system.", a:"Respiratory", b:"Nervous", c:"Circulatory", d:"Digestive", correct:"c"},
    {question:"Which of these is a track event?", a:"Discus", b:"Javelin", c:"High jump", d:"200m race", correct:"d"},

    {question:"The ability to change direction quickly is called _____.", a:"Speed", b:"Agility", c:"Balance", d:"Coordination", correct:"b"},
    {question:"Which of these is a type of recreation?", a:"Working", b:"Studying", c:"Swimming", d:"Cleaning", correct:"c"},
    {question:"The skeleton of the body is made up of _____.", a:"Muscles", b:"Bones", c:"Tissues", d:"Organs", correct:"b"},
    {question:"Which of these is a non-locomotor movement?", a:"Walking", b:"Jumping", c:"Hopping", d:"Bending", correct:"d"},
    {question:"The food that gives the body energy is _____.", a:"Protein", b:"Carbohydrates", c:"Minerals", d:"Water", correct:"b"},
    {question:"Which of these is a safety measure in sports?", a:"Playing without warm-up", b:"Using damaged equipment", c:"Wearing appropriate gear", d:"Playing while injured", correct:"c"},
    {question:"The longest bone in the human body is the _____.", a:"Skull", b:"Rib", c:"Femur", d:"Spine", correct:"c"},
    {question:"Which of these is a ball game?", a:"Swimming", b:"Boxing", c:"Football", d:"Gymnastics", correct:"c"},
    {question:"The exercise that helps to cool down after activity is called _____.", a:"Warm-up", b:"Stretching", c:"Sprinting", d:"Weight training", correct:"b"},
    {question:"Which of these is a water-borne disease?", a:"Malaria", b:"Typhoid", c:"HIV", d:"Diabetes", correct:"b"},

    {question:"The ability to maintain stability while standing or moving is called _____.", a:"Agility", b:"Balance", c:"Coordination", d:"Power", correct:"b"},
    {question:"Which of these is a type of dance?", a:"High jump", b:"Traditional dance", c:"Shot put", d:"Hurdles", correct:"b"},
    {question:"The system responsible for breathing is the _____ system.", a:"Circulatory", b:"Digestive", c:"Respiratory", d:"Nervous", correct:"c"},
    {question:"Which of these is a first aid item?", a:"Plaster", b:"Football", c:"Whistle", d:"Jersey", correct:"a"},
    {question:"The ability to exert force quickly is called _____.", a:"Speed", b:"Power", c:"Endurance", d:"Flexibility", correct:"b"},
    {question:"Which of these is a communicable disease?", a:"Cancer", b:"Diabetes", c:"Tuberculosis", d:"Asthma", correct:"c"},
    {question:"The muscle that pumps blood is the _____.", a:"Lung", b:"Heart", c:"Liver", d:"Kidney", correct:"b"},
    {question:"Which of these is an example of a team sport?", a:"Tennis", b:"Boxing", c:"Basketball", d:"Swimming", correct:"c"},
    {question:"The range of motion around a joint is called _____.", a:"Strength", b:"Flexibility", c:"Endurance", d:"Speed", correct:"b"},
    {question:"Which of these is a nutrient?", a:"Sugar", b:"Protein", c:"Salt", d:"All of the above", correct:"d"},

    {question:"The act of passing a ball to a teammate in football is called _____.", a:"Dribbling", b:"Shooting", c:"Passing", d:"Tackling", correct:"c"},
    {question:"Which of these is an individual sport?", a:"Volleyball", b:"Hockey", c:"Table tennis", d:"Cricket", correct:"c"},
    {question:"The number of players in a football team is _____.", a:"5", b:"7", c:"9", d:"11", correct:"d"},
    {question:"Which of these is a sign of physical fitness?", a:"High blood pressure", b:"Obesity", c:"Good posture", d:"Fatigue", correct:"c"},
    {question:"The substance that makes up about 70% of the human body is _____.", a:"Protein", b:"Fat", c:"Water", d:"Carbohydrate", correct:"c"},
    {question:"Which of these is a type of exercise?", a:"Sleeping", b:"Eating", c:"Jogging", d:"Reading", correct:"c"},
    {question:"The joint that allows movement in all directions is the _____ joint.", a:"Hinge", b:"Ball and socket", c:"Pivot", d:"Gliding", correct:"b"},
    {question:"Which of these is a cause of drug abuse?", a:"Peer pressure", b:"Good health", c:"Exercise", d:"Balanced diet", correct:"a"},
    {question:"The period of recovery after exercise is called _____.", a:"Warm-up", b:"Cool-down", c:"Training", d:"Workout", correct:"b"},
    {question:"Which of these is a track event?", a:"Long jump", b:"High jump", c:"400m race", d:"Javelin", correct:"c"},

    {question:"The ability to perform a movement repeatedly without fatigue is called _____.", a:"Strength", b:"Speed", c:"Endurance", d:"Agility", correct:"c"},
    {question:"Which of these is a non-communicable disease?", a:"Cholera", b:"Malaria", c:"Hypertension", d:"Measles", correct:"c"},
    {question:"The game of basketball was invented by _____.", a:"James Naismith", b:"Pele", c:"Michael Jordan", d:"Usain Bolt", correct:"a"},
    {question:"Which of these is a component of health-related fitness?", a:"Agility", b:"Balance", c:"Cardiovascular endurance", d:"Speed", correct:"c"},
    {question:"The act of hitting the ball with a racket in tennis is called a _____.", a:"Serve", b:"Kick", c:"Throw", d:"Pass", correct:"a"},
    {question:"Which of these is a function of the skeleton?", a:"Digestion", b:"Protection of organs", c:"Circulation", d:"Respiration", correct:"b"},
    {question:"A person who officiates a football match is called a _____.", a:"Coach", b:"Umpire", c:"Referee", d:"Captain", correct:"c"},
    {question:"Which of these is a type of swimming stroke?", a:"Freestyle", b:"High jump", c:"Long jump", d:"Hurdles", correct:"a"},
    {question:"The food class that helps to regulate body processes is _____.", a:"Carbohydrates", b:"Fats", c:"Vitamins", d:"Proteins", correct:"c"},
    {question:"Which of these is a benefit of physical exercise?", a:"Weak bones", b:"Obesity", c:"Weight control", d:"High blood pressure", correct:"c"},

    {question:"The organ that filters waste from the blood is the _____.", a:"Heart", b:"Lung", c:"Kidney", d:"Liver", correct:"c"},
    {question:"Which of these is a manipulative skill?", a:"Running", b:"Jumping", c:"Throwing", d:"Hopping", correct:"c"},
    {question:"The term 'VO2 max' refers to _____.", a:"Maximum strength", b:"Maximum flexibility", c:"Maximum oxygen uptake", d:"Maximum speed", correct:"c"},
    {question:"Which of these is a major muscle group?", a:"Skull", b:"Ribs", c:"Quadriceps", d:"Spine", correct:"c"},
    {question:"The number of players in a basketball team on the court at a time is _____.", a:"5", b:"6", c:"7", d:"8", correct:"a"},
    {question:"Which of these is a symptom of malaria?", a:"Fever", b:"Broken bone", c:"Toothache", d:"Cough", correct:"a"},
    {question:"The ability to use different parts of the body together smoothly is called _____.", a:"Balance", b:"Coordination", c:"Agility", d:"Power", correct:"b"},
    {question:"Which of these is a type of gymnastics?", a:"Floor exercise", b:"High jump", c:"Shot put", d:"Discus", correct:"a"},
    {question:"The food that provides warmth and energy when stored is _____.", a:"Protein", b:"Carbohydrates", c:"Fats and oils", d:"Vitamins", correct:"c"},
    {question:"Which of these is a safety rule in sports?", a:"Play with sharp objects", b:"Ignore the referee", c:"Follow the rules", d:"Play on wet floors", correct:"c"} ],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': [
    {question:"Democracy is a system of government where power belongs to the _____.", a:"Military", b:"People", c:"King", d:"Rich", correct:"b"},
    {question:"The principle that no one is above the law is called _____.", a:"Democracy", b:"Rule of law", c:"UDHR", d:"Civil liberty", correct:"b"},
    {question:"The Universal Declaration of Human Rights (UDHR) was adopted by the _____.", a:"African Union", b:"United Nations", c:"ECOWAS", d:"Commonwealth", correct:"b"},
    {question:"The freedom to express your opinions without fear is known as _____.", a:"Freedom of movement", b:"Freedom of assembly", c:"Freedom of speech", d:"Right to life", correct:"c"},
    {question:"How many articles are in the Universal Declaration of Human Rights?", a:"10", b:"20", c:"30", d:"40", correct:"c"},
    {question:"Which of these is NOT a feature of democracy?", a:"Periodic elections", b:"Military rule", c:"Freedom of press", d:"Majority rule", correct:"b"},
    {question:"The right to vote and be voted for is called _____.", a:"Political right", b:"Social right", c:"Economic right", d:"Cultural right", correct:"a"},
    {question:"The UDHR states that all human beings are born _____.", a:"Rich and powerful", b:"Free and equal", c:"Weak and dependent", d:"Divided by race", correct:"b"},
    {question:"Which arm of government makes laws?", a:"Executive", b:"Judiciary", c:"Legislature", d:"Military", correct:"c"},
    {question:"The law that protects the rights of citizens from government abuse is part of _____.", a:"Customary law", b:"Rule of law", c:"Religious law", d:"Natural law", correct:"b"},
    {question:"The right to life, liberty, and security of person is found in which document?", a:"UDHR", b:"Constitution", c:"Both A and B", d:"None of the above", correct:"c"},
    {question:"In a democracy, the leader of the country is elected through _____.", a:"Appointment", b:"Heredity", c:"Election", d:"Force", correct:"c"},
    {question:"Which of these is a civil liberty?", a:"Right to own a company", b:"Right to a fair hearing", c:"Right to free education", d:"Right to travel abroad", correct:"b"},
    {question:"The concept that government powers are divided into three branches is called _____.", a:"Rule of law", b:"Separation of powers", c:"Democracy", d:"Federalism", correct:"b"},
    {question:"Which generation of human rights focuses on freedom from torture and arbitrary arrest?", a:"First generation", b:"Second generation", c:"Third generation", d:"Fourth generation", correct:"a"},
    {question:"The head of the executive arm of government in Nigeria is the _____.", a:"Chief Justice", b:"Senate President", c:"President", d:"Speaker", correct:"c"},
    {question:"Which of these is a characteristic of the rule of law?", a:"Arbitrary arrest", b:"Equality before the law", c:"Military intervention", d:"Dictatorship", correct:"b"},
    {question:"The UDHR was adopted in which year?", a:"1945", b:"1948", c:"1950", d:"1960", correct:"b"},
    {question:"Freedom of assembly means the right to _____.", a:"Worship freely", b:"Gather peacefully", c:"Travel anywhere", d:"Own property", correct:"b"},
    {question:"Which of these is NOT a type of democracy?", a:"Direct democracy", b:"Indirect democracy", c:"Representative democracy", d:"Military democracy", correct:"d"},

    {question:"The judiciary is responsible for _____.", a:"Making laws", b:"Executing laws", c:"Interpreting laws", d:"Enforcing party discipline", correct:"c"},
    {question:"The principle of 'a government of the people, by the people, and for the people' was stated by _____.", a:"Abraham Lincoln", b:"Thomas Jefferson", c:"George Washington", d:"Nelson Mandela", correct:"a"},
    {question:"Which article of the UDHR states that everyone has the right to education?", a:"Article 1", b:"Article 5", c:"Article 26", d:"Article 30", correct:"c"},
    {question:"The right to own property is classified under which category of rights?", a:"Political rights", b:"Economic rights", c:"Social rights", d:"Civil rights", correct:"b"},
    {question:"Which of these is a violation of civil liberty?", a:"Voting in elections", b:"Peaceful protest", c:"Arbitrary detention", d:"Freedom of speech", correct:"c"},
    {question:"The concept that government must be conducted according to the law is called _____.", a:"Constitutional supremacy", b:"Parliamentary supremacy", c:"Rule of law", d:"Separation of powers", correct:"c"},
    {question:"Which arm of government implements laws?", a:"Legislature", b:"Executive", c:"Judiciary", d:"Press", correct:"b"},
    {question:"The UDHR is considered a _____ document.", a:"Legally binding", b:"Moral and aspirational", c:"Religious", d:"Military", correct:"b"},
    {question:"Which of these is a feature of a democratic election?", a:"Voter intimidation", b:"Secret ballot", c:"Rigging", d:"Violence", correct:"b"},
    {question:"Civil liberties are rights that protect individuals from _____.", a:"Foreign invasion", b:"Government overreach", c:"Economic hardship", d:"Natural disasters", correct:"b"},

    {question:"The right to a fair and public hearing is found in which article of the UDHR?", a:"Article 3", b:"Article 10", c:"Article 15", d:"Article 20", correct:"b"},
    {question:"Which of these is NOT a condition for the rule of law?", a:"Independent judiciary", b:"Supremacy of the constitution", c:"Arbitrary arrests", d:"Equality before the law", correct:"c"},
    {question:"Democracy originated from which ancient civilization?", a:"Rome", b:"Greece", c:"Egypt", d:"China", correct:"b"},
    {question:"The right to participate in government is a _____ right.", a:"Civil", b:"Political", c:"Economic", d:"Social", correct:"b"},
    {question:"Which of these is a limitation to civil liberties?", a:"Public interest", b:"Personal interest", c:"Family interest", d:"Religious interest", correct:"a"},
    {question:"The UDHR was drafted by a committee chaired by _____.", a:"Winston Churchill", b:"Eleanor Roosevelt", c:"Joseph Stalin", d:"Franklin Roosevelt", correct:"b"},
    {question:"Which of these is an example of direct democracy?", a:"Representative government", b:"Referendum", c:"Parliamentary system", d:"Presidential system", correct:"b"},
    {question:"The rule of law requires that government officials _____.", a:"Are above the law", b:"Are also subject to the law", c:"Can ignore the law", d:"Create their own laws", correct:"b"},
    {question:"Freedom from slavery and torture is found in which generation of rights?", a:"First generation", b:"Second generation", c:"Third generation", d:"Fourth generation", correct:"a"},
    {question:"Which of these is a pillar of democracy?", a:"Dictatorship", b:"One-party system", c:"Popular participation", d:"Military junta", correct:"c"},

    {question:"The right to work and fair wages is a _____ right.", a:"Political", b:"Civil", c:"Economic", d:"Cultural", correct:"c"},
    {question:"Which document guarantees civil liberties in Nigeria?", a:"UDHR only", b:"Nigerian Constitution", c:"Party manifesto", d:"Military decree", correct:"b"},
    {question:"The principle of checks and balances allows each arm of government to _____.", a:"Work independently", b:"Oversee and limit the others", c:"Merge with others", d:"Ignore others", correct:"b"},
    {question:"Which of these is NOT a fundamental human right in Nigeria?", a:"Right to life", b:"Right to free housing", c:"Right to dignity", d:"Right to fair hearing", correct:"b"},
    {question:"The term 'democracy' comes from Greek words meaning _____.", a:"Rule by one", b:"Rule by the people", c:"Rule by the rich", d:"Rule by the strong", correct:"b"},
    {question:"Which of these is a form of political participation?", a:"Voting", b:"Sleeping", c:"Watching TV", d:"Eating", correct:"a"},
    {question:"The UDHR applies to _____.", a:"Only citizens of the UN", b:"Only Europeans", c:"All human beings", d:"Only government officials", correct:"c"},
    {question:"Which of these is a civil liberty?", a:"Right to vote", b:"Right to free speech", c:"Right to run for office", d:"Right to form a political party", correct:"b"},
    {question:"The executive arm of government is headed by the _____.", a:"Chief Justice", b:"Speaker", c:"President", d:"Senate President", correct:"c"},
    {question:"Which of these is a violation of the rule of law?", a:"Fair trial", b:"Due process", c:"Arbitrary arrest", d:"Judicial independence", correct:"c"},

    {question:"Second generation human rights are mainly _____ rights.", a:"Political", b:"Civil", c:"Economic, social, and cultural", d:"Collective", correct:"c"},
    {question:"The right to form associations is guaranteed under _____.", a:"Civil liberty", b:"Economic right", c:"Political right", d:"Cultural right", correct:"a"},
    {question:"Which of these is a duty of a citizen in a democracy?", a:"Paying taxes", b:"Ignoring the law", c:"Avoiding elections", d:"Refusing to serve", correct:"a"},
    {question:"The UDHR is not legally binding but has inspired _____.", a:"International treaties", b:"Military coups", c:"Colonialism", d:"Dictatorships", correct:"a"},
    {question:"Which of these is an example of the rule of law?", a:"A president is above the law", b:"A citizen is arrested without trial", c:"A judge is independent", d:"Police arrest arbitrarily", correct:"c"},
    {question:"The right to participate in cultural life is a _____ right.", a:"Political", b:"Civil", c:"Cultural", d:"Economic", correct:"c"},
    {question:"Which of these is a characteristic of democracy?", a:"Censorship", b:"One-party system", c:"Free press", d:"Military rule", correct:"c"},
    {question:"The legislature in Nigeria is called the _____.", a:"Executive Council", b:"National Assembly", c:"Supreme Court", d:"Federal Cabinet", correct:"b"},
    {question:"Which of these is a third-generation human right?", a:"Right to life", b:"Right to development", c:"Right to work", d:"Right to vote", correct:"b"},
    {question:"Civil liberties can be limited during _____.", a:"Elections", b:"Times of emergency", c:"Peaceful protests", d:"Religious gatherings", correct:"b"}
],
        'CCA': [],
        'Business Studies': [],
        'Espanol': [],
        'Agric': [],
        'Home Economics': []
    },
    'JSS2': {},
    'JSS3': {},

    // SENIOR SECONDARY
    'SS1': {
        'Mathematics': [],
        'English': [],
        'Biology': [],
        'Physics': [],
        'Chemistry': [],
        'Government': [],
        'Literature': [],
        'Geography': [],
        'Commerce': [],
        'Marketing': [],
        'Financial Accounting': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': []
    },
    'SS2': {},
    'SS3': {}
};