const questionBank = {
    // PRIMARY SCHOOL
    'Pry1': {
        'Mathematics': [
            {question:"2 + 2 = ?", a:"3", b:"4", c:"5", d:"6", correct:"b"},
            {question:"5 x 6 = ?", a:"30", b:"25", c:"40", d:"20", correct:"a"}
        ],
        'English': [],
        'Basic Science': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': [],
        'CCA': [],
        'Home Economics': [],
        'Quantitative Reasoning': [],
        'Verbal Reasoning': []
    },
    'Pry2': {},
    'Pry3': {},
    'Pry4': {},
    'Pry5': {},

    // JUNIOR SECONDARY
    'JSS1': {
        'Mathematics': [],
        'English': [{question:"The word that rhymes with 'cat' is _____.", a:"Cot", b:"Cut", c:"Bat", d:"Kit", correct:"c"},
{question:"A group of words that has a subject and a verb and makes complete sense is called a _____.", a:"Phrase", b:"Clause", c:"Sentence", d:"Paragraph", correct:"b"},
{question:"The past tense of 'teach' is _____.", a:"Teached", b:"Taught", c:"Teachd", d:"Thought", correct:"b"},
{question:"An adjective is a word that _____.", a:"Shows action", b:"Describes a noun", c:"Joins two words", d:"Replaces a noun", correct:"b"},
{question:"'The man is very tall.' The word 'very' in this sentence is an _____.", a:"Noun", b:"Adverb", c:"Verb", d:"Interjection", correct:"b"},
{question:"The feminine gender of 'actor' is _____.", a:"Actress", b:"Actorine", c:"Actoress", d:"Actrix", correct:"a"},
{question:"A sentence that expresses a strong emotion ends with a(n) _____.", a:"Full stop", b:"Question mark", c:"Exclamation mark", d:"Comma", correct:"c"},
{question:"The plural form of 'child' is _____.", a:"Childs", b:"Childes", c:"Children", d:"Childrens", correct:"c"},
{question:"Which of these is a proper noun?", a:"City", b:"River", c:"Lagos", d:"Teacher", correct:"c"},
{question:"The word 'beautiful' is an example of a(n) _____.", a:"Noun", b:"Verb", c:"Adjective", d:"Adverb", correct:"c"},
{question:"The part of a letter that contains the message is the _____.", a:"Salutation", b:"Body", c:"Closing", d:"Heading", correct:"b"},
{question:"He _____ to school every day.", a:"Go", b:"Goes", c:"Going", d:"Gone", correct:"b"},
{question:"Which word is a synonym for 'happy'?", a:"Sad", b:"Joyful", c:"Angry", d:"Tired", correct:"b"},
{question:"A word that means the opposite of another word is called a(n) _____.", a:"Synonym", b:"Homonym", c:"Antonym", d:"Acronym", correct:"c"},
{question:"'We are going to the market.' The pronoun in this sentence is _____.", a:"We", b:"going", c:"market", d:"the", correct:"a"},
{question:"Which of the following is a vowel?", a:"b", b:"c", c:"a", d:"d", correct:"c"},
{question:"A long narrative fictional story is a _____.", a:"Poem", b:"Novel", c:"Play", d:"Letter", correct:"b"},
{question:"'She sings beautifully.' The word 'beautifully' tells us _____.", a:"Where", b:"When", c:"How", d:"Why", correct:"c"},
{question:"The tense used to express an action that has already happened is _____.", a:"Present", b:"Future", c:"Past", d:"Continuous", correct:"c"},
{question:"Which punctuation mark is used to ask a question?", a:"Full stop", b:"Comma", c:"Question mark", d:"Exclamation mark", correct:"c"},
{question:"The word that rhymes with 'cat' is _____.", a:"Cot", b:"Cut", c:"Bat", d:"Kit", correct:"c"},
{question:"A group of words that has a subject and a verb and makes complete sense is called a _____.", a:"Phrase", b:"Clause", c:"Sentence", d:"Paragraph", correct:"b"},
{question:"The past tense of 'teach' is _____.", a:"Teached", b:"Taught", c:"Teachd", d:"Thought", correct:"b"},
{question:"An adjective is a word that _____.", a:"Shows action", b:"Describes a noun", c:"Joins two words", d:"Replaces a noun", correct:"b"},
{question:"'The man is very tall.' The word 'very' in this sentence is an _____.", a:"Noun", b:"Adverb", c:"Verb", d:"Interjection", correct:"b"},
{question:"The feminine gender of 'actor' is _____.", a:"Actress", b:"Actorine", c:"Actoress", d:"Actrix", correct:"a"},
{question:"A sentence that expresses a strong emotion ends with a(n) _____.", a:"Full stop", b:"Question mark", c:"Exclamation mark", d:"Comma", correct:"c"},
{question:"The plural form of 'child' is _____.", a:"Childs", b:"Childes", c:"Children", d:"Childrens", correct:"c"},
{question:"Which of these is a proper noun?", a:"City", b:"River", c:"Lagos", d:"Teacher", correct:"c"},
{question:"The word 'beautiful' is an example of a(n) _____.", a:"Noun", b:"Verb", c:"Adjective", d:"Adverb", correct:"c"},
{question:"The part of a letter that contains the message is the _____.", a:"Salutation", b:"Body", c:"Closing", d:"Heading", correct:"b"},
{question:"He _____ to school every day.", a:"Go", b:"Goes", c:"Going", d:"Gone", correct:"b"},
{question:"Which word is a synonym for 'happy'?", a:"Sad", b:"Joyful", c:"Angry", d:"Tired", correct:"b"},
{question:"A word that means the opposite of another word is called a(n) _____.", a:"Synonym", b:"Homonym", c:"Antonym", d:"Acronym", correct:"c"},
{question:"'We are going to the market.' The pronoun in this sentence is _____.", a:"We", b:"going", c:"market", d:"the", correct:"a"},
{question:"Which of the following is a vowel?", a:"b", b:"c", c:"a", d:"d", correct:"c"},
{question:"A long narrative fictional story is a _____.", a:"Poem", b:"Novel", c:"Play", d:"Letter", correct:"b"},
{question:"'She sings beautifully.' The word 'beautifully' tells us _____.", a:"Where", b:"When", c:"How", d:"Why", correct:"c"},
{question:"The tense used to express an action that has already happened is _____.", a:"Present", b:"Future", c:"Past", d:"Continuous", correct:"c"},
{question:"Which punctuation mark is used to ask a question?", a:"Full stop", b:"Comma", c:"Question mark", d:"Exclamation mark", correct:"c"}],
        'Basic Science': [],
        'PHE': [ {question:"Physical education is the education of the _____.", a:"Mind only", b:"Body only", c:"Body and mind through physical activity", d:"Spirit", correct:"c"},
    {question:"Which of these is a locomotor movement?", a:"Bending", b:"Twisting", c:"Running", d:"Stretching", correct:"c"},
    {question:"The ability to perform daily activities without fatigue is called _____.", a:"Physical fitness", b:"Physical education", c:"Recreation", d:"Sports", correct:"a"},
    {question:"Which of these is a component of physical fitness?", a:"Agility", b:"Intelligence", c:"Creativity", d:"Memory", correct:"a"},
    {question:"The food that builds the body is called _____.", a:"Carbohydrates", b:"Fats", c:"Proteins", d:"Vitamins", correct:"c"},
    {question:"Which of these is a field event in athletics?", a:"100m race", b:"Shot put", c:"4x100m relay", d:"Hurdles", correct:"b"},
    {question:"The organ that pumps blood around the body is the _____.", a:"Lung", b:"Brain", c:"Heart", d:"Kidney", correct:"c"},
    {question:"Which of these is a warm-up exercise?", a:"Sprinting", b:"Jogging", c:"Weightlifting", d:"Long jump", correct:"b"},
    {question:"The system that consists of the heart, blood, and blood vessels is called the _____ system.", a:"Respiratory", b:"Nervous", c:"Circulatory", d:"Digestive", correct:"c"},
    {question:"Which of these is a track event?", a:"Discus", b:"Javelin", c:"High jump", d:"200m race", correct:"d"},

    {question:"The ability to change direction quickly is called _____.", a:"Speed", b:"Agility", c:"Balance", d:"Coordination", correct:"b"},
    {question:"Which of these is a type of recreation?", a:"Working", b:"Studying", c:"Swimming", d:"Cleaning", correct:"c"},
    {question:"The skeleton of the body is made up of _____.", a:"Muscles", b:"Bones", c:"Tissues", d:"Organs", correct:"b"},
    {question:"Which of these is a non-locomotor movement?", a:"Walking", b:"Jumping", c:"Hopping", d:"Bending", correct:"d"},
    {question:"The food that gives the body energy is _____.", a:"Protein", b:"Carbohydrates", c:"Minerals", d:"Water", correct:"b"},
    {question:"Which of these is a safety measure in sports?", a:"Playing without warm-up", b:"Using damaged equipment", c:"Wearing appropriate gear", d:"Playing while injured", correct:"c"},
    {question:"The longest bone in the human body is the _____.", a:"Skull", b:"Rib", c:"Femur", d:"Spine", correct:"c"},
    {question:"Which of these is a ball game?", a:"Swimming", b:"Boxing", c:"Football", d:"Gymnastics", correct:"c"},
    {question:"The exercise that helps to cool down after activity is called _____.", a:"Warm-up", b:"Stretching", c:"Sprinting", d:"Weight training", correct:"b"},
    {question:"Which of these is a water-borne disease?", a:"Malaria", b:"Typhoid", c:"HIV", d:"Diabetes", correct:"b"},

    {question:"The ability to maintain stability while standing or moving is called _____.", a:"Agility", b:"Balance", c:"Coordination", d:"Power", correct:"b"},
    {question:"Which of these is a type of dance?", a:"High jump", b:"Traditional dance", c:"Shot put", d:"Hurdles", correct:"b"},
    {question:"The system responsible for breathing is the _____ system.", a:"Circulatory", b:"Digestive", c:"Respiratory", d:"Nervous", correct:"c"},
    {question:"Which of these is a first aid item?", a:"Plaster", b:"Football", c:"Whistle", d:"Jersey", correct:"a"},
    {question:"The ability to exert force quickly is called _____.", a:"Speed", b:"Power", c:"Endurance", d:"Flexibility", correct:"b"},
    {question:"Which of these is a communicable disease?", a:"Cancer", b:"Diabetes", c:"Tuberculosis", d:"Asthma", correct:"c"},
    {question:"The muscle that pumps blood is the _____.", a:"Lung", b:"Heart", c:"Liver", d:"Kidney", correct:"b"},
    {question:"Which of these is an example of a team sport?", a:"Tennis", b:"Boxing", c:"Basketball", d:"Swimming", correct:"c"},
    {question:"The range of motion around a joint is called _____.", a:"Strength", b:"Flexibility", c:"Endurance", d:"Speed", correct:"b"},
    {question:"Which of these is a nutrient?", a:"Sugar", b:"Protein", c:"Salt", d:"All of the above", correct:"d"},

    {question:"The act of passing a ball to a teammate in football is called _____.", a:"Dribbling", b:"Shooting", c:"Passing", d:"Tackling", correct:"c"},
    {question:"Which of these is an individual sport?", a:"Volleyball", b:"Hockey", c:"Table tennis", d:"Cricket", correct:"c"},
    {question:"The number of players in a football team is _____.", a:"5", b:"7", c:"9", d:"11", correct:"d"},
    {question:"Which of these is a sign of physical fitness?", a:"High blood pressure", b:"Obesity", c:"Good posture", d:"Fatigue", correct:"c"},
    {question:"The substance that makes up about 70% of the human body is _____.", a:"Protein", b:"Fat", c:"Water", d:"Carbohydrate", correct:"c"},
    {question:"Which of these is a type of exercise?", a:"Sleeping", b:"Eating", c:"Jogging", d:"Reading", correct:"c"},
    {question:"The joint that allows movement in all directions is the _____ joint.", a:"Hinge", b:"Ball and socket", c:"Pivot", d:"Gliding", correct:"b"},
    {question:"Which of these is a cause of drug abuse?", a:"Peer pressure", b:"Good health", c:"Exercise", d:"Balanced diet", correct:"a"},
    {question:"The period of recovery after exercise is called _____.", a:"Warm-up", b:"Cool-down", c:"Training", d:"Workout", correct:"b"},
    {question:"Which of these is a track event?", a:"Long jump", b:"High jump", c:"400m race", d:"Javelin", correct:"c"},

    {question:"The ability to perform a movement repeatedly without fatigue is called _____.", a:"Strength", b:"Speed", c:"Endurance", d:"Agility", correct:"c"},
    {question:"Which of these is a non-communicable disease?", a:"Cholera", b:"Malaria", c:"Hypertension", d:"Measles", correct:"c"},
    {question:"The game of basketball was invented by _____.", a:"James Naismith", b:"Pele", c:"Michael Jordan", d:"Usain Bolt", correct:"a"},
    {question:"Which of these is a component of health-related fitness?", a:"Agility", b:"Balance", c:"Cardiovascular endurance", d:"Speed", correct:"c"},
    {question:"The act of hitting the ball with a racket in tennis is called a _____.", a:"Serve", b:"Kick", c:"Throw", d:"Pass", correct:"a"},
    {question:"Which of these is a function of the skeleton?", a:"Digestion", b:"Protection of organs", c:"Circulation", d:"Respiration", correct:"b"},
    {question:"A person who officiates a football match is called a _____.", a:"Coach", b:"Umpire", c:"Referee", d:"Captain", correct:"c"},
    {question:"Which of these is a type of swimming stroke?", a:"Freestyle", b:"High jump", c:"Long jump", d:"Hurdles", correct:"a"},
    {question:"The food class that helps to regulate body processes is _____.", a:"Carbohydrates", b:"Fats", c:"Vitamins", d:"Proteins", correct:"c"},
    {question:"Which of these is a benefit of physical exercise?", a:"Weak bones", b:"Obesity", c:"Weight control", d:"High blood pressure", correct:"c"},

    {question:"The organ that filters waste from the blood is the _____.", a:"Heart", b:"Lung", c:"Kidney", d:"Liver", correct:"c"},
    {question:"Which of these is a manipulative skill?", a:"Running", b:"Jumping", c:"Throwing", d:"Hopping", correct:"c"},
    {question:"The term 'VO2 max' refers to _____.", a:"Maximum strength", b:"Maximum flexibility", c:"Maximum oxygen uptake", d:"Maximum speed", correct:"c"},
    {question:"Which of these is a major muscle group?", a:"Skull", b:"Ribs", c:"Quadriceps", d:"Spine", correct:"c"},
    {question:"The number of players in a basketball team on the court at a time is _____.", a:"5", b:"6", c:"7", d:"8", correct:"a"},
    {question:"Which of these is a symptom of malaria?", a:"Fever", b:"Broken bone", c:"Toothache", d:"Cough", correct:"a"},
    {question:"The ability to use different parts of the body together smoothly is called _____.", a:"Balance", b:"Coordination", c:"Agility", d:"Power", correct:"b"},
    {question:"Which of these is a type of gymnastics?", a:"Floor exercise", b:"High jump", c:"Shot put", d:"Discus", correct:"a"},
    {question:"The food that provides warmth and energy when stored is _____.", a:"Protein", b:"Carbohydrates", c:"Fats and oils", d:"Vitamins", correct:"c"},
    {question:"Which of these is a safety rule in sports?", a:"Play with sharp objects", b:"Ignore the referee", c:"Follow the rules", d:"Play on wet floors", correct:"c"} ],
        'Digital Tech': [
{question:"A computer is an electronic device that _____.", a:"Cooks food", b:"Processes data", c:"Washes clothes", d:"Builds houses", correct:"b"},
{question:"Which of these is an input device?", a:"Monitor", b:"Printer", c:"Keyboard", d:"Speaker", correct:"c"},
{question:"The brain of the computer is called the _____.", a:"Monitor", b:"CPU", c:"Keyboard", d:"Mouse", correct:"b"},
{question:"Which of these is an output device?", a:"Mouse", b:"Scanner", c:"Monitor", d:"Keyboard", correct:"c"},
{question:"The physical parts of a computer that you can touch are called _____.", a:"Software", b:"Hardware", c:"Data", d:"Programs", correct:"b"},
{question:"Which of these is a storage device?", a:"Flash drive", b:"Keyboard", c:"Mouse", d:"Monitor", correct:"a"},
{question:"The programs that run on a computer are called _____.", a:"Hardware", b:"Software", c:"Devices", d:"Components", correct:"b"},
{question:"Which of these is an example of system software?", a:"Microsoft Word", b:"Operating system", c:"Excel", d:"PowerPoint", correct:"b"},
{question:"The device used to point and click on items on the screen is the _____.", a:"Keyboard", b:"Monitor", c:"Mouse", d:"Printer", correct:"c"},
{question:"Which of these is a type of computer?", a:"Desktop", b:"Laptop", c:"Tablet", d:"All of the above", correct:"d"},

{question:"The screen that displays information from the computer is the _____.", a:"CPU", b:"Keyboard", c:"Monitor", d:"Mouse", correct:"c"},
{question:"Which of these is used to print documents?", a:"Scanner", b:"Printer", c:"Monitor", d:"Speaker", correct:"b"},
{question:"The process of starting a computer is called _____.", a:"Shutting down", b:"Booting", c:"Restarting", d:"Sleeping", correct:"b"},
{question:"Which of these is a word processing software?", a:"Excel", b:"PowerPoint", c:"Microsoft Word", d:"Access", correct:"c"},
{question:"The key used to cancel an operation is the _____ key.", a:"Enter", b:"Spacebar", c:"Esc", d:"Tab", correct:"c"},
{question:"Which of these is a social media platform?", a:"Facebook", b:"Google Chrome", c:"Microsoft Word", d:"Windows", correct:"a"},
{question:"The device that converts digital signals to analog for internet connection is a _____.", a:"Router", b:"Modem", c:"Switch", d:"Hub", correct:"b"},
{question:"Which of these is a search engine?", a:"Google", b:"Facebook", c:"Instagram", d:"WhatsApp", correct:"a"},
{question:"The unauthorized access to computer systems is called _____.", a:"Hacking", b:"Booting", c:"Programming", d:"Debugging", correct:"a"},
{question:"Which of these is a computer virus?", a:"Trojan", b:"Malaria", c:"Typhoid", d:"Cholera", correct:"a"},

{question:"The key used to type in uppercase letters is the _____ key.", a:"Shift", b:"Ctrl", c:"Alt", d:"Enter", correct:"a"},
{question:"Which of these is a spreadsheet software?", a:"Word", b:"Excel", c:"PowerPoint", d:"Publisher", correct:"b"},
{question:"The process of saving a file for future use is called _____.", a:"Deleting", b:"Saving", c:"Editing", d:"Formatting", correct:"b"},
{question:"Which of these is an internet browser?", a:"Chrome", b:"Facebook", c:"WhatsApp", d:"Instagram", correct:"a"},
{question:"The address of a website is called a _____.", a:"URL", b:"CPU", c:"RAM", d:"ROM", correct:"a"},
{question:"Which of these is a type of network?", a:"LAN", b:"WAN", c:"MAN", d:"All of the above", correct:"d"},
{question:"The temporary memory that stores data when the computer is on is called _____.", a:"ROM", b:"RAM", c:"Hard drive", d:"Flash drive", correct:"b"},
{question:"Which of these is an operating system?", a:"Windows", b:"Word", c:"Excel", d:"PowerPoint", correct:"a"},
{question:"The process of sending an email is called _____.", a:"Emailing", b:"Posting", c:"Messaging", d:"Chatting", correct:"a"},
{question:"Which of these is a computer language?", a:"Python", b:"English", c:"French", d:"Spanish", correct:"a"},

{question:"The device that displays information on paper is a _____.", a:"Monitor", b:"Printer", c:"Speaker", d:"Scanner", correct:"b"},
{question:"Which of these is a pointing device?", a:"Keyboard", b:"Mouse", c:"Monitor", d:"Printer", correct:"b"},
{question:"The permanent memory of the computer is called _____.", a:"RAM", b:"ROM", c:"Cache", d:"Register", correct:"b"},
{question:"Which of these is a presentation software?", a:"Word", b:"Excel", c:"PowerPoint", d:"Access", correct:"c"},
{question:"The key used to delete characters to the left of the cursor is the _____ key.", a:"Delete", b:"Backspace", c:"Enter", d:"Spacebar", correct:"b"},
{question:"Which of these is a component of the CPU?", a:"ALU", b:"CU", c:"MU", d:"All of the above", correct:"d"},
{question:"The process of arranging data in a specific order is called _____.", a:"Sorting", b:"Searching", c:"Editing", d:"Formatting", correct:"a"},
{question:"Which of these is a type of computer security?", a:"Antivirus", b:"Password", c:"Firewall", d:"All of the above", correct:"d"},
{question:"The device that captures images and converts them to digital format is a _____.", a:"Printer", b:"Scanner", c:"Monitor", d:"Speaker", correct:"b"},
{question:"Which of these is a storage capacity unit?", a:"Byte", b:"Meter", c:"Liter", d:"Gram", correct:"a"},

{question:"The process of transferring files from the internet to a computer is called _____.", a:"Uploading", b:"Downloading", c:"Streaming", d:"Browsing", correct:"b"},
{question:"Which of these is a computer ethics issue?", a:"Plagiarism", b:"Hacking", c:"Software piracy", d:"All of the above", correct:"d"},
{question:"The key used to move the cursor to the beginning of a line is the _____ key.", a:"End", b:"Home", c:"Page Up", d:"Page Down", correct:"b"},
{question:"Which of these is a database software?", a:"Word", b:"Excel", c:"Access", d:"PowerPoint", correct:"c"},
{question:"The process of combining two or more cells in a spreadsheet is called _____.", a:"Merging", b:"Splitting", c:"Aligning", d:"Formatting", correct:"a"},
{question:"Which of these is a type of computer threat?", a:"Virus", b:"Worm", c:"Trojan horse", d:"All of the above", correct:"d"},
{question:"The device that produces sound from a computer is a _____.", a:"Monitor", b:"Speaker", c:"Printer", d:"Scanner", correct:"b"},
{question:"Which of these is a function of the operating system?", a:"Memory management", b:"File management", c:"Process management", d:"All of the above", correct:"d"},
{question:"The key used to refresh a page is the _____ key.", a:"F1", b:"F2", c:"F5", d:"F12", correct:"c"},
{question:"Which of these is a cloud storage service?", a:"Google Drive", b:"OneDrive", c:"Dropbox", d:"All of the above", correct:"d"},

{question:"The process of creating a duplicate of a file is called _____.", a:"Copying", b:"Moving", c:"Deleting", d:"Renaming", correct:"a"},
{question:"Which of these is a type of computer network topology?", a:"Bus", b:"Star", c:"Ring", d:"All of the above", correct:"d"},
{question:"The device that connects a computer to a network is a _____.", a:"Modem", b:"Router", c:"Network card", d:"All of the above", correct:"d"},
{question:"Which of these is an example of application software?", a:"Windows", b:"Linux", c:"Microsoft Word", d:"macOS", correct:"c"},
{question:"The process of correcting errors in a program is called _____.", a:"Debugging", b:"Programming", c:"Coding", d:"Compiling", correct:"a"},
{question:"Which of these is a computer output device?", a:"Keyboard", b:"Mouse", c:"Plotter", d:"Scanner", correct:"c"},
{question:"The key combination used to copy selected text is _____.", a:"Ctrl + C", b:"Ctrl + V", c:"Ctrl + X", d:"Ctrl + Z", correct:"a"},
{question:"Which of these is a social media risk?", a:"Cyberbullying", b:"Identity theft", c:"Privacy invasion", d:"All of the above", correct:"d"},
{question:"The process of turning off a computer properly is called _____.", a:"Shutting down", b:"Restarting", c:"Sleeping", d:"Hibernating", correct:"a"},
{question:"Which of these is a characteristic of a computer?", a:"Speed", b:"Accuracy", c:"Diligence", d:"All of the above", correct:"d"}
],
        'CRS': [],
        'Nigerian History': [],
        'SCS': [
    {question:"Democracy is a system of government where power belongs to the _____.", a:"Military", b:"People", c:"King", d:"Rich", correct:"b"},
    {question:"The principle that no one is above the law is called _____.", a:"Democracy", b:"Rule of law", c:"UDHR", d:"Civil liberty", correct:"b"},
    {question:"The Universal Declaration of Human Rights (UDHR) was adopted by the _____.", a:"African Union", b:"United Nations", c:"ECOWAS", d:"Commonwealth", correct:"b"},
    {question:"The freedom to express your opinions without fear is known as _____.", a:"Freedom of movement", b:"Freedom of assembly", c:"Freedom of speech", d:"Right to life", correct:"c"},
    {question:"How many articles are in the Universal Declaration of Human Rights?", a:"10", b:"20", c:"30", d:"40", correct:"c"},
    {question:"Which of these is NOT a feature of democracy?", a:"Periodic elections", b:"Military rule", c:"Freedom of press", d:"Majority rule", correct:"b"},
    {question:"The right to vote and be voted for is called _____.", a:"Political right", b:"Social right", c:"Economic right", d:"Cultural right", correct:"a"},
    {question:"The UDHR states that all human beings are born _____.", a:"Rich and powerful", b:"Free and equal", c:"Weak and dependent", d:"Divided by race", correct:"b"},
    {question:"Which arm of government makes laws?", a:"Executive", b:"Judiciary", c:"Legislature", d:"Military", correct:"c"},
    {question:"The law that protects the rights of citizens from government abuse is part of _____.", a:"Customary law", b:"Rule of law", c:"Religious law", d:"Natural law", correct:"b"},
    {question:"The right to life, liberty, and security of person is found in which document?", a:"UDHR", b:"Constitution", c:"Both A and B", d:"None of the above", correct:"c"},
    {question:"In a democracy, the leader of the country is elected through _____.", a:"Appointment", b:"Heredity", c:"Election", d:"Force", correct:"c"},
    {question:"Which of these is a civil liberty?", a:"Right to own a company", b:"Right to a fair hearing", c:"Right to free education", d:"Right to travel abroad", correct:"b"},
    {question:"The concept that government powers are divided into three branches is called _____.", a:"Rule of law", b:"Separation of powers", c:"Democracy", d:"Federalism", correct:"b"},
    {question:"Which generation of human rights focuses on freedom from torture and arbitrary arrest?", a:"First generation", b:"Second generation", c:"Third generation", d:"Fourth generation", correct:"a"},
    {question:"The head of the executive arm of government in Nigeria is the _____.", a:"Chief Justice", b:"Senate President", c:"President", d:"Speaker", correct:"c"},
    {question:"Which of these is a characteristic of the rule of law?", a:"Arbitrary arrest", b:"Equality before the law", c:"Military intervention", d:"Dictatorship", correct:"b"},
    {question:"The UDHR was adopted in which year?", a:"1945", b:"1948", c:"1950", d:"1960", correct:"b"},
    {question:"Freedom of assembly means the right to _____.", a:"Worship freely", b:"Gather peacefully", c:"Travel anywhere", d:"Own property", correct:"b"},
    {question:"Which of these is NOT a type of democracy?", a:"Direct democracy", b:"Indirect democracy", c:"Representative democracy", d:"Military democracy", correct:"d"},

    {question:"The judiciary is responsible for _____.", a:"Making laws", b:"Executing laws", c:"Interpreting laws", d:"Enforcing party discipline", correct:"c"},
    {question:"The principle of 'a government of the people, by the people, and for the people' was stated by _____.", a:"Abraham Lincoln", b:"Thomas Jefferson", c:"George Washington", d:"Nelson Mandela", correct:"a"},
    {question:"Which article of the UDHR states that everyone has the right to education?", a:"Article 1", b:"Article 5", c:"Article 26", d:"Article 30", correct:"c"},
    {question:"The right to own property is classified under which category of rights?", a:"Political rights", b:"Economic rights", c:"Social rights", d:"Civil rights", correct:"b"},
    {question:"Which of these is a violation of civil liberty?", a:"Voting in elections", b:"Peaceful protest", c:"Arbitrary detention", d:"Freedom of speech", correct:"c"},
    {question:"The concept that government must be conducted according to the law is called _____.", a:"Constitutional supremacy", b:"Parliamentary supremacy", c:"Rule of law", d:"Separation of powers", correct:"c"},
    {question:"Which arm of government implements laws?", a:"Legislature", b:"Executive", c:"Judiciary", d:"Press", correct:"b"},
    {question:"The UDHR is considered a _____ document.", a:"Legally binding", b:"Moral and aspirational", c:"Religious", d:"Military", correct:"b"},
    {question:"Which of these is a feature of a democratic election?", a:"Voter intimidation", b:"Secret ballot", c:"Rigging", d:"Violence", correct:"b"},
    {question:"Civil liberties are rights that protect individuals from _____.", a:"Foreign invasion", b:"Government overreach", c:"Economic hardship", d:"Natural disasters", correct:"b"},

    {question:"The right to a fair and public hearing is found in which article of the UDHR?", a:"Article 3", b:"Article 10", c:"Article 15", d:"Article 20", correct:"b"},
    {question:"Which of these is NOT a condition for the rule of law?", a:"Independent judiciary", b:"Supremacy of the constitution", c:"Arbitrary arrests", d:"Equality before the law", correct:"c"},
    {question:"Democracy originated from which ancient civilization?", a:"Rome", b:"Greece", c:"Egypt", d:"China", correct:"b"},
    {question:"The right to participate in government is a _____ right.", a:"Civil", b:"Political", c:"Economic", d:"Social", correct:"b"},
    {question:"Which of these is a limitation to civil liberties?", a:"Public interest", b:"Personal interest", c:"Family interest", d:"Religious interest", correct:"a"},
    {question:"The UDHR was drafted by a committee chaired by _____.", a:"Winston Churchill", b:"Eleanor Roosevelt", c:"Joseph Stalin", d:"Franklin Roosevelt", correct:"b"},
    {question:"Which of these is an example of direct democracy?", a:"Representative government", b:"Referendum", c:"Parliamentary system", d:"Presidential system", correct:"b"},
    {question:"The rule of law requires that government officials _____.", a:"Are above the law", b:"Are also subject to the law", c:"Can ignore the law", d:"Create their own laws", correct:"b"},
    {question:"Freedom from slavery and torture is found in which generation of rights?", a:"First generation", b:"Second generation", c:"Third generation", d:"Fourth generation", correct:"a"},
    {question:"Which of these is a pillar of democracy?", a:"Dictatorship", b:"One-party system", c:"Popular participation", d:"Military junta", correct:"c"},

    {question:"The right to work and fair wages is a _____ right.", a:"Political", b:"Civil", c:"Economic", d:"Cultural", correct:"c"},
    {question:"Which document guarantees civil liberties in Nigeria?", a:"UDHR only", b:"Nigerian Constitution", c:"Party manifesto", d:"Military decree", correct:"b"},
    {question:"The principle of checks and balances allows each arm of government to _____.", a:"Work independently", b:"Oversee and limit the others", c:"Merge with others", d:"Ignore others", correct:"b"},
    {question:"Which of these is NOT a fundamental human right in Nigeria?", a:"Right to life", b:"Right to free housing", c:"Right to dignity", d:"Right to fair hearing", correct:"b"},
    {question:"The term 'democracy' comes from Greek words meaning _____.", a:"Rule by one", b:"Rule by the people", c:"Rule by the rich", d:"Rule by the strong", correct:"b"},
    {question:"Which of these is a form of political participation?", a:"Voting", b:"Sleeping", c:"Watching TV", d:"Eating", correct:"a"},
    {question:"The UDHR applies to _____.", a:"Only citizens of the UN", b:"Only Europeans", c:"All human beings", d:"Only government officials", correct:"c"},
    {question:"Which of these is a civil liberty?", a:"Right to vote", b:"Right to free speech", c:"Right to run for office", d:"Right to form a political party", correct:"b"},
    {question:"The executive arm of government is headed by the _____.", a:"Chief Justice", b:"Speaker", c:"President", d:"Senate President", correct:"c"},
    {question:"Which of these is a violation of the rule of law?", a:"Fair trial", b:"Due process", c:"Arbitrary arrest", d:"Judicial independence", correct:"c"},

    {question:"Second generation human rights are mainly _____ rights.", a:"Political", b:"Civil", c:"Economic, social, and cultural", d:"Collective", correct:"c"},
    {question:"The right to form associations is guaranteed under _____.", a:"Civil liberty", b:"Economic right", c:"Political right", d:"Cultural right", correct:"a"},
    {question:"Which of these is a duty of a citizen in a democracy?", a:"Paying taxes", b:"Ignoring the law", c:"Avoiding elections", d:"Refusing to serve", correct:"a"},
    {question:"The UDHR is not legally binding but has inspired _____.", a:"International treaties", b:"Military coups", c:"Colonialism", d:"Dictatorships", correct:"a"},
    {question:"Which of these is an example of the rule of law?", a:"A president is above the law", b:"A citizen is arrested without trial", c:"A judge is independent", d:"Police arrest arbitrarily", correct:"c"},
    {question:"The right to participate in cultural life is a _____ right.", a:"Political", b:"Civil", c:"Cultural", d:"Economic", correct:"c"},
    {question:"Which of these is a characteristic of democracy?", a:"Censorship", b:"One-party system", c:"Free press", d:"Military rule", correct:"c"},
    {question:"The legislature in Nigeria is called the _____.", a:"Executive Council", b:"National Assembly", c:"Supreme Court", d:"Federal Cabinet", correct:"b"},
    {question:"Which of these is a third-generation human right?", a:"Right to life", b:"Right to development", c:"Right to work", d:"Right to vote", correct:"b"},
    {question:"Civil liberties can be limited during _____.", a:"Elections", b:"Times of emergency", c:"Peaceful protests", d:"Religious gatherings", correct:"b"}
],
        'CCA': [],
        'Business Studies': [],
        'Espanol': [],
        'Agric': [{question:"Agriculture is defined as the _____.", a:"Art of cooking food", b:"Science of building houses", c:"Art and science of cultivating crops and rearing animals", d:"Study of rocks", correct:"c"},
{question:"Which of these is a branch of agriculture?", a:"Carpentry", b:"Crop production", c:"Plumbing", d:"Painting", correct:"b"},
{question:"The practice of growing only one type of crop on a piece of land is called _____.", a:"Mixed cropping", b:"Monocropping", c:"Crop rotation", d:"Intercropping", correct:"b"},
{question:"Which of these is a cereal crop?", a:"Cassava", b:"Yam", c:"Maize", d:"Potato", correct:"c"},
{question:"Animals that live in water are called _____.", a:"Terrestrial animals", b:"Aquatic animals", c:"Arboreal animals", d:"Aerial animals", correct:"b"},
{question:"The process of loosening the soil is called _____.", a:"Planting", b:"Harvesting", c:"Tillage", d:"Irrigation", correct:"c"},
{question:"Which of these is a farm implement?", a:"Hoe", b:"Spoon", c:"Cup", d:"Plate", correct:"a"},
{question:"The part of a plant that absorbs water and nutrients is the _____.", a:"Stem", b:"Leaf", c:"Root", d:"Flower", correct:"c"},
{question:"Which of these is a leguminous crop?", a:"Rice", b:"Groundnut", c:"Millet", d:"Sorghum", correct:"b"},
{question:"The rearing of fish is called _____.", a:"Apiculture", b:"Aquaculture", c:"Sericulture", d:"Horticulture", correct:"b"},

{question:"Which of these is a source of farm power?", a:"Human", b:"Animal", c:"Machine", d:"All of the above", correct:"d"},
{question:"The process of removing unwanted plants from the farm is called _____.", a:"Weeding", b:"Pruning", c:"Mulching", d:"Thinning", correct:"a"},
{question:"Which of these is a tuber crop?", a:"Maize", b:"Rice", c:"Cassava", d:"Beans", correct:"c"},
{question:"Animals that chew the cud are called _____.", a:"Ruminants", b:"Omnivores", c:"Carnivores", d:"Rodents", correct:"a"},
{question:"The practice of planting crops on a slope following contour lines is called _____.", a:"Terracing", b:"Contour ploughing", c:"Shifting cultivation", d:"Mulching", correct:"b"},
{question:"Which of these is a vegetable crop?", a:"Tomato", b:"Millet", c:"Sorghum", d:"Rice", correct:"a"},
{question:"The male parent of a farm animal is called a _____.", a:"Dam", b:"Sire", c:"Calf", d:"Lamb", correct:"b"},
{question:"Which of these is a method of preserving fish?", a:"Sun drying", b:"Soaking", c:"Boiling", d:"Frying", correct:"a"},
{question:"The layer of soil that is most fertile is the _____.", a:"Topsoil", b:"Subsoil", c:"Bedrock", d:"Clay layer", correct:"a"},
{question:"Which of these is a farm animal?", a:"Lion", b:"Elephant", c:"Goat", d:"Zebra", correct:"c"},

{question:"The process of providing water to crops artificially is called _____.", a:"Irrigation", b:"Drainage", c:"Mulching", d:"Tilling", correct:"a"},
{question:"Which of these is a fruit crop?", a:"Cabbage", b:"Lettuce", c:"Orange", d:"Spinach", correct:"c"},
{question:"The young one of a cow is called a _____.", a:"Lamb", b:"Kid", c:"Calf", d:"Foal", correct:"c"},
{question:"Which of these is a type of soil?", a:"Sandy soil", b:"Glass soil", c:"Plastic soil", d:"Metal soil", correct:"a"},
{question:"The practice of keeping bees is called _____.", a:"Apiculture", b:"Aquaculture", c:"Sericulture", d:"Silviculture", correct:"a"},
{question:"Which of these is a perennial crop?", a:"Maize", b:"Rice", c:"Cocoa", d:"Beans", correct:"c"},
{question:"The process of cutting down trees in the forest is called _____.", a:"Afforestation", b:"Reforestation", c:"Deforestation", d:"Forestry", correct:"c"},
{question:"Which of these is a farm structure?", a:"Pen", b:"Bedroom", c:"Kitchen", d:"Bathroom", correct:"a"},
{question:"The organ used for breathing in fish is the _____.", a:"Lung", b:"Gill", c:"Skin", d:"Mouth", correct:"b"},
{question:"Which of these is a pest of crops?", a:"Earthworm", b:"Grasshopper", c:"Ladybird", d:"Butterfly", correct:"b"},

{question:"The process of separating grains from chaff is called _____.", a:"Winnowing", b:"Harvesting", c:"Threshing", d:"Planting", correct:"a"},
{question:"Which of these is a root crop?", a:"Carrot", b:"Maize", c:"Rice", d:"Wheat", correct:"a"},
{question:"The young one of a goat is called a _____.", a:"Lamb", b:"Kid", c:"Calf", d:"Pup", correct:"b"},
{question:"Which of these is a disease of crops?", a:"Malaria", b:"Typhoid", c:"Blight", d:"Cholera", correct:"c"},
{question:"The process of cutting and gathering mature crops is called _____.", a:"Planting", b:"Weeding", c:"Harvesting", d:"Threshing", correct:"c"},
{question:"Which of these is a non-ruminant animal?", a:"Cow", b:"Sheep", c:"Goat", d:"Pig", correct:"d"},
{question:"The part of the plant responsible for photosynthesis is the _____.", a:"Root", b:"Stem", c:"Leaf", d:"Flower", correct:"c"},
{question:"Which of these is a type of manure?", a:"Urea", b:"Compost", c:"NPK", d:"All of the above", correct:"b"},
{question:"The process of removing branches from a tree is called _____.", a:"Weeding", b:"Pruning", c:"Mulching", d:"Thinning", correct:"b"},
{question:"Which of these is a cereal crop?", a:"Yam", b:"Cassava", c:"Sorghum", d:"Potato", correct:"c"},

{question:"The home of a fish is called a _____.", a:"Pond", b:"Cage", c:"Tank", d:"All of the above", correct:"d"},
{question:"Which of these is a factor affecting agricultural production?", a:"Climate", b:"Soil", c:"Pests", d:"All of the above", correct:"d"},
{question:"The process of covering the soil with plant materials to retain moisture is called _____.", a:"Mulching", b:"Tillage", c:"Irrigation", d:"Drainage", correct:"a"},
{question:"Which of these is a farm record?", a:"Diary", b:"Notebook", c:"Farm inventory", d:"All of the above", correct:"d"},
{question:"The young one of a pig is called a _____.", a:"Lamb", b:"Kid", c:"Piglet", d:"Calf", correct:"c"},
{question:"Which of these is a method of planting?", a:"Broadcasting", b:"Drilling", c:"Dibbling", d:"All of the above", correct:"d"},
{question:"The process of raising crops and animals together is called _____.", a:"Mixed farming", b:"Monoculture", c:"Crop rotation", d:"Shifting cultivation", correct:"a"},
{question:"Which of these is a storage structure for grains?", a:"Silo", b:"Basket", c:"Sack", d:"All of the above", correct:"d"},
{question:"The food made by plants during photosynthesis is _____.", a:"Protein", b:"Fat", c:"Glucose", d:"Vitamin", correct:"c"},
{question:"Which of these is a breed of cattle?", a:"White Fulani", b:"West African Dwarf", c:"N'dama", d:"All of the above", correct:"d"},

{question:"The process of removing excess seedlings to give space for growth is called _____.", a:"Thinning", b:"Weeding", c:"Pruning", d:"Mulching", correct:"a"},
{question:"Which of these is a soil nutrient?", a:"Nitrogen", b:"Phosphorus", c:"Potassium", d:"All of the above", correct:"d"},
{question:"The young one of a sheep is called a _____.", a:"Lamb", b:"Kid", c:"Calf", d:"Foal", correct:"a"},
{question:"Which of these is a climatic factor?", a:"Rainfall", b:"Temperature", c:"Sunlight", d:"All of the above", correct:"d"},
{question:"The process of tilling the land for the first time is called _____.", a:"Secondary tillage", b:"Primary tillage", c:"Weeding", d:"Mulching", correct:"b"},
{question:"Which of these is a tree crop?", a:"Oil palm", b:"Maize", c:"Rice", d:"Millet", correct:"a"},
{question:"The female parent of a farm animal is called a _____.", a:"Sire", b:"Dam", c:"Offspring", d:"Young", correct:"b"},
{question:"Which of these is a source of farm credit?", a:"Bank", b:"Cooperative society", c:"Government", d:"All of the above", correct:"d"},
{question:"The process of giving birth in cattle is called _____.", a:"Parturition", b:"Calving", c:"Farrowing", d:"Lambing", correct:"b"},
{question:"Which of these is a benefit of agriculture?", a:"Food production", b:"Employment", c:"Income generation", d:"All of the above", correct:"d"} ],
        'Home Economics': []
    },
    'JSS2': {
        'JSS2': {
'SCS': [
{question:"A system of government in which citizens vote for representatives to make laws on their behalf is called _____.", a:"Direct democracy", b:"Representative democracy", c:"Autocracy", d:"Oligarchy", correct:"b"},
{question:"The principle that the law applies equally to all citizens, including government officials, is called _____.", a:"Separation of powers", b:"Rule of law", c:"Democracy", d:"Constitutional supremacy", correct:"b"},
{question:"The UDHR was proclaimed by the United Nations General Assembly on _____.", a:"December 10, 1945", b:"December 10, 1948", c:"October 24, 1945", d:"January 1, 1948", correct:"b"},
{question:"The right to peacefully assemble and associate with others is guaranteed under _____.", a:"Civil liberty", b:"Political liberty", c:"Economic liberty", d:"Cultural liberty", correct:"a"},
{question:"Article 1 of the UDHR states that all human beings are born free and equal in _____.", a:"Wealth and power", b:"Dignity and rights", c:"Strength and intelligence", d:"Culture and religion", correct:"b"},
{question:"Which of these is a characteristic of democracy?", a:"Absence of elections", b:"Military intervention", c:"Popular sovereignty", d:"Dictatorship", correct:"c"},
{question:"The right to a fair trial is found in which article of the UDHR?", a:"Article 3", b:"Article 5", c:"Article 10", d:"Article 15", correct:"c"},
{question:"The term 'civil liberty' refers to _____.", a:"Rights that protect individuals from government abuse", b:"Rights to participate in government", c:"Rights to economic benefits", d:"Rights to cultural expression", correct:"a"},
{question:"Which arm of government interprets the law?", a:"Executive", b:"Legislature", c:"Judiciary", d:"Military", correct:"c"},
{question:"The concept that government powers are divided into three branches to prevent tyranny is called _____.", a:"Rule of law", b:"Separation of powers", c:"Federalism", d:"Checks and balances", correct:"b"},
{question:"Which of these is a first-generation human right?", a:"Right to work", b:"Right to education", c:"Freedom from torture", d:"Right to health care", correct:"c"},
{question:"In a democracy, the will of the _____ prevails.", a:"Minority", b:"Majority", c:"Ruler", d:"Military", correct:"b"},
{question:"Which of these is a limitation on civil liberties?", a:"National security", b:"Public order", c:"Public health", d:"All of the above", correct:"d"},
{question:"The UDHR consists of a preamble and how many articles?", a:"20", b:"25", c:"30", d:"35", correct:"c"},
{question:"The doctrine that allows each branch of government to limit the power of the other branches is called _____.", a:"Separation of powers", b:"Checks and balances", c:"Rule of law", d:"Federalism", correct:"b"},
{question:"Which of these is NOT a condition for the rule of law?", a:"Independent judiciary", b:"Supremacy of the constitution", c:"Arbitrary arrest", d:"Equality before the law", correct:"c"},
{question:"Second-generation human rights are also known as _____ rights.", a:"Civil and political", b:"Economic, social, and cultural", c:"Collective and solidarity", d:"Fundamental", correct:"b"},
{question:"The right to freedom of thought, conscience, and religion is found in which article of the UDHR?", a:"Article 1", b:"Article 5", c:"Article 18", d:"Article 25", correct:"c"},
{question:"Which of these is a form of political participation?", a:"Voting in elections", b:"Joining a political party", c:"Running for office", d:"All of the above", correct:"d"},
{question:"A government in which the executive is drawn from and accountable to the legislature is called a _____ system.", a:"Presidential", b:"Parliamentary", c:"Military", d:"Monarchical", correct:"b"},
{question:"The Nigerian Constitution guarantees civil liberties in _____.", a:"Chapter 1", b:"Chapter 2", c:"Chapter 4", d:"Chapter 7", correct:"c"},
{question:"The right to own property is classified as a _____ right.", a:"Civil", b:"Political", c:"Economic", d:"Social", correct:"c"},
{question:"Which of these is a violation of the rule of law?", a:"Due process", b:"Fair trial", c:"Ex post facto law", d:"Judicial independence", correct:"c"},
{question:"The concept that the constitution is the highest law in the land is called _____.", a:"Rule of law", b:"Constitutional supremacy", c:"Separation of powers", d:"Parliamentary supremacy", correct:"b"},
{question:"Third-generation human rights include the right to _____.", a:"Vote", b:"Work", c:"Development", d:"Fair trial", correct:"c"},
{question:"Which of these is a feature of the rule of law?", a:"Punishment without trial", b:"Arbitrary arrest", c:"Independent judiciary", d:"Dictatorship", correct:"c"},
{question:"The head of the judiciary in Nigeria is the _____.", a:"President", b:"Chief Justice of Nigeria", c:"Attorney General", d:"Senate President", correct:"b"},
{question:"The UDHR is not a legally binding treaty, but it has influenced _____.", a:"National constitutions", b:"International human rights law", c:"Regional human rights instruments", d:"All of the above", correct:"d"},
{question:"Which of these is a civil liberty?", a:"Right to vote", b:"Right to run for office", c:"Freedom of speech", d:"Right to form a political party", correct:"c"},
{question:"The process of removing an elected official from office before their term expires is called _____.", a:"Election", b:"Recall", c:"Impeachment", d:"Referendum", correct:"c"},
{question:"Which article of the UDHR prohibits torture and cruel treatment?", a:"Article 3", b:"Article 5", c:"Article 7", d:"Article 9", correct:"b"},
{question:"The principle that government must be conducted according to the law is called _____.", a:"Democracy", b:"Rule of law", c:"Federalism", d:"Republicanism", correct:"b"},
{question:"Which of these is a type of democracy?", a:"Direct democracy", b:"Indirect democracy", c:"Representative democracy", d:"All of the above", correct:"d"},
{question:"The right to social security and to work is found in which article of the UDHR?", a:"Article 18", b:"Article 20", c:"Article 22", d:"Article 25", correct:"c"},
{question:"Which of these is a duty of a citizen in a democracy?", a:"Obeying the law", b:"Paying taxes", c:"Serving as a witness", d:"All of the above", correct:"d"},
{question:"The legislature in Nigeria is bicameral, meaning it has _____.", a:"One house", b:"Two houses", c:"Three houses", d:"Four houses", correct:"b"},
{question:"Which of these is an example of direct democracy?", a:"Representative government", b:"Presidential system", c:"Plebiscite", d:"Parliamentary system", correct:"c"},
{question:"The rule of law requires that government actions be based on _____.", a:"The ruler's whim", b:"Public opinion", c:"Authorized law", d:"Military decree", correct:"c"},
{question:"The right to freedom from arbitrary arrest is found in which article of the UDHR?", a:"Article 3", b:"Article 5", c:"Article 9", d:"Article 12", correct:"c"},
{question:"Which of these is a pillar of democracy?", a:"Popular participation", b:"Periodic elections", c:"Accountability", d:"All of the above", correct:"d"},
{question:"The right to education is found in which article of the UDHR?", a:"Article 23", b:"Article 24", c:"Article 26", d:"Article 27", correct:"c"},
{question:"Which of these is a function of the executive arm of government?", a:"Making laws", b:"Interpreting laws", c:"Implementing laws", d:"Adjudicating disputes", correct:"c"},
{question:"The concept that all citizens have the right to participate in the political process is called _____.", a:"Rule of law", b:"Political participation", c:"Separation of powers", d:"Constitutional supremacy", correct:"b"},
{question:"Which of these is NOT a fundamental human right in Nigeria?", a:"Right to life", b:"Right to dignity", c:"Right to free housing", d:"Right to fair hearing", correct:"c"},
{question:"The term 'sovereignty' means _____.", a:"Subordination to foreign powers", b:"Supreme power and authority", c:"Division of power", d:"Absence of power", correct:"b"},
{question:"Which of these is a method of human rights protection?", a:"Courts", b:"Human Rights Commission", c:"Civil society organizations", d:"All of the above", correct:"d"},
{question:"The UDHR applies to _____.", a:"Only citizens", b:"Only adults", c:"All human beings", d:"Only officials", correct:"c"},
{question:"Which of these is a political right?", a:"Right to life", b:"Right to education", c:"Right to vote", d:"Right to health", correct:"c"},
{question:"The executive arm of government is responsible for _____.", a:"Lawmaking", b:"Law interpretation", c:"Law enforcement", d:"Judicial review", correct:"c"},
{question:"Which of these is a condition for free and fair elections?", a:"Independent commission", b:"Secret ballot", c:"Freedom of speech", d:"All of the above", correct:"d"},
{question:"The right to participate in cultural life is found in which article of the UDHR?", a:"Article 25", b:"Article 26", c:"Article 27", d:"Article 28", correct:"c"},
{question:"Which of these is a responsibility of government in a democracy?", a:"Protecting rights", b:"Providing public goods", c:"Maintaining order", d:"All of the above", correct:"d"},
{question:"The concept that citizens can criticize the government is part of _____.", a:"Civil liberty", b:"Political liberty", c:"Both A and B", d:"None", correct:"c"},
{question:"Which of these is a limitation on the rule of law?", a:"State of emergency", b:"Independent judiciary", c:"Free press", d:"Accountability", correct:"a"},
{question:"The right to work is found in which article of the UDHR?", a:"Article 20", b:"Article 22", c:"Article 23", d:"Article 24", correct:"c"},
{question:"Which of these is a human rights violation?", a:"Arbitrary detention", b:"Torture", c:"Discrimination", d:"All of the above", correct:"d"},
{question:"Popular sovereignty means _____.", a:"Military rule", b:"Power belongs to the people", c:"Judiciary supremacy", d:"Executive control", correct:"b"},
{question:"Which of these is a function of the legislature?", a:"Budget approval", b:"Oversight", c:"Lawmaking", d:"All of the above", correct:"d"},
{question:"The right to freedom of movement is in which article of the UDHR?", a:"Article 10", b:"Article 12", c:"Article 13", d:"Article 15", correct:"c"},
{question:"Civil liberties are essential for the functioning of _____.", a:"Dictatorship", b:"Democracy", c:"Monarchy", d:"Theocracy", correct:"b"}
]
},
    },
    'JSS3': {},

    // SENIOR SECONDARY
    'SS1': {
        'Mathematics': [],
        'English': [],
        'Biology': [],
        'Physics': [],
        'Chemistry': [],
        'Government': [],
        'Literature': [],
        'Geography': [],
        'Commerce': [],
        'Marketing': [],
        'Financial Accounting': [],
        'PHE': [],
        'Digital Tech': [],
        'CRS': [],
        'Nigerian History': [],
        'SCS': []
    },
    'SS2': {},
    'SS3': {}
};